export const NAME_LIST = [
  { name: "Charlotte Taylor", company: "Video Platform", department: "Data Science" },
  { name: "Joseph Taylor", company: "PR Solutions", department: "Public Relations" },
  { name: "Isabella Nguyen", company: "Advertising Agency", department: "Compliance" },
  { name: "Lily King", company: "Future Systems", department: "Compliance" },
  { name: "Alexander Nguyen", company: "Cyber Security Plus", department: "Planning" },
  { name: "Harper Smith", company: "Innovate Labs", department: "Product Management" },
  { name: "Sophia Mitchell", company: "Fitness Tech", department: "Human Resources" },
  { name: "Evelyn Campbell", company: "Fitness Tech", department: "Business Intelligence" },
  { name: "Mason Miller", company: "Food Delivery Co", department: "Planning" },
  { name: "Avery Rivera", company: "Fitness Tech", department: "Game Design" },
  { name: "Alexander Rivera", company: "Catering Services", department: "Human Resources" },
  { name: "Ava Lopez", company: "Travel Tech", department: "Property Management" },
  { name: "Charlotte Carter", company: "Analytics Pro", department: "Booking Systems" },
  { name: "Andrew Taylor", company: "Travel Tech", department: "Renewable Energy" },
  { name: "Liam Rivera", company: "Medical Devices", department: "IT Security" },
  { name: "Lucas Lewis", company: "Social Media Inc", department: "Planning" },
  { name: "Ella Anderson", company: "Sports Management", department: "Community Management" },
  { name: "Charlotte Torres", company: "Video Platform", department: "Editorial" },
  { name: "Andrew Rodriguez", company: "Resort Management", department: "Administration" },
  { name: "Liam Carter", company: "Medical Devices", department: "Logistics" },
  { name: "Christopher Roberts", company: "Retail Solutions", department: "Planning" },
  { name: "Scarlett Lee", company: "Publishing House", department: "Finance" },
  { name: "Noah Robinson", company: "Software House", department: "Customer Support" },
  { name: "Amelia Jones", company: "Cloud Networks", department: "Marketing" },
  { name: "Nora Hall", company: "Food Delivery Co", department: "Medical Technology" },
  { name: "Emily Green", company: "Fitness Tech", department: "Broadcasting" },
  { name: "Henry Taylor", company: "Innovate Labs", department: "Community Management" },
  { name: "Sebastian Young", company: "Event Management", department: "Learning Solutions" },
  { name: "Lucas Perez", company: "Global Enterprises", department: "Athlete Relations" },
  { name: "Christian Garcia", company: "Video Platform", department: "Editorial" },
  { name: "Ava Ramirez", company: "Innovate Labs", department: "IT Security" },
  { name: "Nathan Williams", company: "Food Delivery Co", department: "Athlete Relations" },
  { name: "Benjamin Young", company: "Cloud Networks", department: "Strategy" },
  { name: "Andrew Rodriguez", company: "Transport Solutions", department: "Planning" },
  { name: "Henry White", company: "Medical Devices", department: "Content" },
  { name: "Alexander Garcia", company: "Travel Tech", department: "Community Management" },
  { name: "Samuel Hill", company: "PR Solutions", department: "Customer Support" },
  { name: "Evelyn Nelson", company: "Spa & Wellness", department: "Game Design" },
  { name: "Nora King", company: "Software House", department: "Data Science" },
  { name: "Owen Adams", company: "E-Commerce Hub", department: "Legal" },
  { name: "Amelia Clark", company: "Cloud Networks", department: "Human Resources" },
  { name: "Grace Hill", company: "Digital Marketing Co", department: "Marketing" },
  { name: "Jack Rivera", company: "PR Solutions", department: "Training" },
  { name: "Benjamin Miller", company: "Catering Services", department: "Marketing" },
  { name: "Hannah King", company: "Video Platform", department: "Design" },
  { name: "Michael Thompson", company: "Advertising Agency", department: "Content" },
  { name: "Sebastian Martin", company: "Entertainment Group", department: "Content Acquisition" },
  { name: "Zoey Young", company: "Media Group", department: "Customer Support" },
  { name: "Nora Williams", company: "Energy Systems", department: "IT Security" },
  { name: "Emma Lopez", company: "Music Streaming", department: "Learning Solutions" },
  { name: "Grace Nelson", company: "Web Innovations", department: "Business Intelligence" },
  { name: "Mia Anderson", company: "Food Delivery Co", department: "Research & Development" },
  { name: "Jack Lewis", company: "Innovate Labs", department: "Creative" },
  { name: "David Williams", company: "E-Commerce Hub", department: "Supply Chain" },
  { name: "Nora Robinson", company: "Analytics Pro", department: "Legal" },
  { name: "Harper Gonzalez", company: "Fitness Tech", department: "Editorial" },
  { name: "Ethan Mitchell", company: "Publishing House", department: "Finance" },
  { name: "Hannah Flores", company: "Fitness Tech", department: "Planning" },
  { name: "Christian Sanchez", company: "Entertainment Group", department: "Marketing" },
  { name: "Andrew Anderson", company: "Hotel Chain", department: "Accounting" },
  { name: "Victoria Hernandez", company: "Nutrition Apps", department: "Marketing" },
  { name: "Nathan Flores", company: "Manufacturing Tech", department: "Human Resources" },
  { name: "Hannah Lee", company: "Beauty Products", department: "Research" },
  { name: "Mason Flores", company: "Data Corp", department: "Game Design" },
  { name: "Christopher Baker", company: "Resort Management", department: "Production" },
  { name: "Noah Wright", company: "Fashion Tech", department: "Broadcasting" },
  { name: "Elizabeth Jackson", company: "Pharmaceutical Co", department: "Booking Systems" },
  { name: "Andrew Clark", company: "Energy Systems", department: "Development" },
  { name: "Christian King", company: "Beauty Products", department: "Renewable Energy" },
  { name: "Emily Brown", company: "Cyber Security Plus", department: "Customer Support" },
  { name: "Ella Sanchez", company: "Digital Dynamics", department: "Production" },
  { name: "Lucas Thomas", company: "Beauty Products", department: "Development" },
  { name: "Ava Anderson", company: "Innovate Labs", department: "Health Science" },
  { name: "Mason Torres", company: "Advertising Agency", department: "Training" },
  { name: "Daniel Hernandez", company: "Medical Devices", department: "Clinical Trials" },
  { name: "Charlotte Mitchell", company: "Web Innovations", department: "Innovation" },
  { name: "Charlotte Roberts", company: "Video Platform", department: "Training" },
  { name: "David Anderson", company: "E-Commerce Hub", department: "Customer Support" },
  { name: "Charlotte Lewis", company: "BlockChain Ventures", department: "Business Intelligence" },
  { name: "Isaac Lewis", company: "Travel Tech", department: "Research & Development" },
  { name: "Jack Lee", company: "Future Systems", department: "Therapy" },
  { name: "Liam Young", company: "Beauty Products", department: "IT Security" },
  { name: "Joseph Lewis", company: "Finance Tech", department: "Development" },
  { name: "Isaac Sanchez", company: "Digital Marketing Co", department: "Editorial" },
  { name: "Matthew Williams", company: "Gaming Studios", department: "Innovation" },
  { name: "Scarlett Moore", company: "Entertainment Group", department: "Quality Assurance" },
  { name: "Samuel Mitchell", company: "Gaming Studios", department: "Customer Support" },
  { name: "Mia Campbell", company: "Video Platform", department: "Renewable Energy" },
  { name: "Jack Torres", company: "Energy Systems", department: "Design" },
  { name: "William Young", company: "Future Systems", department: "Development" },
  { name: "Nathan Lewis", company: "Mobile First", department: "Therapy" },
  { name: "Sophia Rodriguez", company: "Global Enterprises", department: "Legal" },
  { name: "Emma Gonzalez", company: "Sports Management", department: "Accounting" },
  { name: "William Torres", company: "Advertising Agency", department: "Customer Support" },
  { name: "Christopher Williams", company: "Event Management", department: "Broadcasting" },
  { name: "Alexander Martin", company: "Tech Solutions Inc", department: "Content Acquisition" },
  { name: "Isabella Taylor", company: "AI Solutions", department: "Editorial" },
  { name: "Daniel Jackson", company: "Biotech Innovations", department: "Genetics" },
  { name: "Elizabeth Rivera", company: "Sports Management", department: "Merchandising" },
  { name: "Abigail Scott", company: "Innovate Labs", department: "Design Studio" },
  { name: "Ella Taylor", company: "Publishing House", department: "Booking Systems" },
  { name: "Isaac Robinson", company: "Retail Solutions", department: "Engineering" },
  { name: "Christian Garcia", company: "Cyber Security Plus", department: "Innovation" },
  { name: "Sebastian Green", company: "Education Tech", department: "Development" },
  { name: "Addison Hill", company: "Innovate Labs", department: "Content Acquisition" },
  { name: "Avery Baker", company: "Food Delivery Co", department: "Human Resources" },
  { name: "Amelia Wright", company: "Video Platform", department: "Therapy" },
  { name: "Charlotte Hill", company: "Advertising Agency", department: "Medical Technology" },
  { name: "Abigail Young", company: "Innovate Labs", department: "Community Management" },
  { name: "James Nelson", company: "Music Streaming", department: "Research & Development" },
  { name: "Owen Thompson", company: "Hotel Chain", department: "Strategy" },
  { name: "Sofia Lee", company: "BlockChain Ventures", department: "Quality Assurance" },
  { name: "Jack Robinson", company: "Medical Devices", department: "Renewable Energy" },
  { name: "William Jackson", company: "Entertainment Group", department: "Property Management" },
  { name: "Matthew Garcia", company: "Entertainment Group", department: "Product Management" },
  { name: "James Clark", company: "Healthcare IT", department: "Sales" },
  { name: "Hannah Green", company: "Tech Solutions Inc", department: "Renewable Energy" },
  { name: "David Campbell", company: "Mobile First", department: "Strategy" },
  { name: "Mason Lewis", company: "Real Estate Tech", department: "Genetics" },
  { name: "Sebastian Hernandez", company: "Platform Services", department: "Design" },
  { name: "Charlotte Carter", company: "Data Corp", department: "Product Management" },
  { name: "Olivia Wilson", company: "Music Streaming", department: "Production" },
  { name: "Michael Thompson", company: "E-Commerce Hub", department: "Genetics" },
  { name: "Avery Brown", company: "Energy Systems", department: "Editorial" },
  { name: "Joseph Gonzalez", company: "Cyber Security Plus", department: "Game Design" },
  { name: "Owen Roberts", company: "Mobile First", department: "Accounting" },
  { name: "Ella Wilson", company: "BlockChain Ventures", department: "Supply Chain" },
  { name: "Sofia Brown", company: "Energy Systems", department: "Broadcasting" },
  { name: "Avery Ramirez", company: "Manufacturing Tech", department: "Human Resources" },
  { name: "Samuel Hall", company: "Medical Devices", department: "Broadcasting" },
  { name: "Christian Brown", company: "Global Enterprises", department: "Design" },
  { name: "Addison Young", company: "Spa & Wellness", department: "Human Resources" },
  { name: "Abigail Lewis", company: "Real Estate Tech", department: "Engineering" },
  { name: "Mason Johnson", company: "Spa & Wellness", department: "Medical Technology" },
  { name: "Chloe Garcia", company: "Media Group", department: "Product Management" },
  { name: "Victoria Anderson", company: "Smart Technologies", department: "Community Management" },
  { name: "Avery Nelson", company: "Education Tech", department: "Property Management" },
  { name: "Ava Nguyen", company: "AI Solutions", department: "Compliance" },
  { name: "Isaac Harris", company: "AI Solutions", department: "Research" },
  { name: "Olivia Anderson", company: "Video Platform", department: "Innovation" },
  { name: "Olivia Jackson", company: "Food Delivery Co", department: "Public Relations" },
  { name: "Isabella Perez", company: "Real Estate Tech", department: "Quality Assurance" },
  { name: "Mason Scott", company: "Smart Technologies", department: "Innovation" },
  { name: "Samuel Brown", company: "E-Commerce Hub", department: "Learning Solutions" },
  { name: "Avery Anderson", company: "Innovate Labs", department: "Creative" },
  { name: "Ryan Jones", company: "Data Corp", department: "Genetics" },
  { name: "Mason Ramirez", company: "Cyber Security Plus", department: "Engineering" },
  { name: "Hannah Perez", company: "Real Estate Tech", department: "Creative" },
  { name: "Ella Gonzalez", company: "Finance Tech", department: "Training" },
  { name: "Nathan Lopez", company: "Software House", department: "Finance" },
  { name: "Nora Green", company: "Cyber Security Plus", department: "Research & Development" },
  { name: "Emma Harris", company: "Real Estate Tech", department: "Health Science" },
  { name: "Harper Garcia", company: "Transport Solutions", department: "Quality Assurance" },
  { name: "Ava Rodriguez", company: "Manufacturing Tech", department: "Booking Systems" },
  { name: "Evelyn Lopez", company: "Real Estate Tech", department: "Operations" },
  { name: "Sebastian Rodriguez", company: "Data Corp", department: "Strategy" },
  { name: "Abigail Wright", company: "Innovate Labs", department: "DevOps" },
  { name: "Owen Mitchell", company: "Cyber Security Plus", department: "Product Management" },
  { name: "Benjamin Walker", company: "Event Management", department: "Content" },
  { name: "Victoria Perez", company: "Analytics Pro", department: "Logistics" },
  { name: "Christopher Scott", company: "Digital Dynamics", department: "Production" },
  { name: "Olivia Lewis", company: "Data Corp", department: "Clinical Trials" },
  { name: "Sophia Adams", company: "Pharmaceutical Co", department: "Community Management" },
  { name: "Isaac Brown", company: "Catering Services", department: "Game Design" },
  { name: "Harper Gonzalez", company: "Video Platform", department: "Supply Chain" },
  { name: "Isabella Brown", company: "Medical Devices", department: "Supply Chain" },
  { name: "Benjamin Adams", company: "Entertainment Group", department: "Medical Technology" },
  { name: "Nathan Davis", company: "Travel Tech", department: "Consulting" },
  { name: "Jack Gonzalez", company: "Transport Solutions", department: "Quality Assurance" },
  { name: "Lucas Harris", company: "Platform Services", department: "Administration" },
  { name: "William Thomas", company: "Manufacturing Tech", department: "Logistics" },
  { name: "Ava Taylor", company: "Web Innovations", department: "Renewable Energy" },
  { name: "Alexander Flores", company: "Mobile First", department: "Broadcasting" },
  { name: "Owen Nelson", company: "PR Solutions", department: "Content" },
  { name: "Jack Adams", company: "Media Group", department: "Community Management" },
  { name: "Olivia Roberts", company: "Software House", department: "Development" },
  { name: "Scarlett Davis", company: "Fashion Tech", department: "Engineering" },
  { name: "Benjamin Moore", company: "Cloud Networks", department: "Broadcasting" },
  { name: "Chloe Martin", company: "BlockChain Ventures", department: "Quality Assurance" },
  { name: "Sofia Davis", company: "Education Tech", department: "Booking Systems" },
  { name: "Isaac Wright", company: "Beauty Products", department: "Sales" },
  { name: "Andrew Garcia", company: "Gaming Studios", department: "Creative" },
  { name: "Benjamin Lewis", company: "Cloud Networks", department: "Health Science" },
  { name: "Matthew Clark", company: "Education Tech", department: "Creative" },
  { name: "Lucas Wilson", company: "PR Solutions", department: "Legal" },
  { name: "Noah Harris", company: "Spa & Wellness", department: "Game Design" },
  { name: "Henry Wright", company: "Fashion Tech", department: "Design Studio" },
  { name: "Christopher Smith", company: "Healthcare IT", department: "Editorial" },
  { name: "Sofia Walker", company: "Social Media Inc", department: "Compliance" },
  { name: "James Ramirez", company: "Fashion Tech", department: "DevOps" },
  { name: "Sebastian Moore", company: "Travel Tech", department: "Business Intelligence" },
  { name: "Grace Lewis", company: "Manufacturing Tech", department: "Machine Learning" },
  { name: "William Martinez", company: "Retail Solutions", department: "Genetics" },
  { name: "Avery Lewis", company: "Social Media Inc", department: "Machine Learning" },
  { name: "Amelia Nelson", company: "Energy Systems", department: "Content" },
  { name: "Ethan Hernandez", company: "Data Corp", department: "Design Studio" },
  { name: "William Davis", company: "Resort Management", department: "Health Science" },
  { name: "Sebastian Adams", company: "Analytics Pro", department: "Marketing" },
  { name: "Benjamin Thompson", company: "Nutrition Apps", department: "Editorial" },
  { name: "Victoria Mitchell", company: "Biotech Innovations", department: "Research" },
  { name: "Sebastian Sanchez", company: "Education Tech", department: "Operations" },
  { name: "Noah Scott", company: "Manufacturing Tech", department: "Clinical Trials" },
  { name: "Henry Brown", company: "Nutrition Apps", department: "Administration" },
  { name: "Zoey Martinez", company: "Education Tech", department: "Marketing" },
  { name: "Sofia Baker", company: "Transport Solutions", department: "Renewable Energy" },
  { name: "Amelia Clark", company: "Tech Solutions Inc", department: "Content Acquisition" },
  { name: "Samuel Gonzalez", company: "Fashion Tech", department: "Human Resources" },
  { name: "Mason Campbell", company: "Smart Technologies", department: "Design" },
  { name: "William Harris", company: "Event Management", department: "Health Science" },
  { name: "Isaac Carter", company: "Resort Management", department: "Customer Support" },
  { name: "Charlotte Thomas", company: "Healthcare IT", department: "Learning Solutions" },
  { name: "Matthew Wilson", company: "Music Streaming", department: "Supply Chain" },
  { name: "Joseph Nguyen", company: "Hotel Chain", department: "IT Security" },
  { name: "Nora Jackson", company: "Tech Solutions Inc", department: "Therapy" },
  { name: "Lucas Hill", company: "Video Platform", department: "Quality Assurance" },
  { name: "Sebastian Green", company: "BlockChain Ventures", department: "Game Design" },
  { name: "Mason Nelson", company: "Event Management", department: "Community Management" },
  { name: "Scarlett Rodriguez", company: "Global Enterprises", department: "Medical Technology" },
  { name: "Alexander Harris", company: "Retail Solutions", department: "IT Security" },
  { name: "Zoey Gonzalez", company: "Web Innovations", department: "Data Science" },
  { name: "James Baker", company: "Beauty Products", department: "Finance" },
  { name: "Hannah Martinez", company: "Biotech Innovations", department: "Training" },
  { name: "Isabella Sanchez", company: "Fitness Tech", department: "Consulting" },
  { name: "Benjamin Garcia", company: "Smart Technologies", department: "Therapy" },
  { name: "Elizabeth Perez", company: "Video Platform", department: "Research" },
  { name: "Ethan Nguyen", company: "AI Solutions", department: "Research & Development" },
  { name: "Emma Flores", company: "Catering Services", department: "Booking Systems" },
  { name: "Isabella Brown", company: "Fitness Tech", department: "Broadcasting" },
  { name: "Avery Torres", company: "Event Management", department: "Machine Learning" },
  { name: "Michael Martin", company: "Cloud Networks", department: "Therapy" },
  { name: "Nathan Baker", company: "Food Delivery Co", department: "Quality Assurance" },
  { name: "Samuel Sanchez", company: "Resort Management", department: "Editorial" },
  { name: "Ella Harris", company: "Digital Dynamics", department: "Operations" },
  { name: "Henry Scott", company: "Digital Dynamics", department: "Data Science" },
  { name: "Isaac Rodriguez", company: "Event Management", department: "Product Management" },
  { name: "Christopher Anderson", company: "Energy Systems", department: "Therapy" },
  { name: "Benjamin Ramirez", company: "Sports Management", department: "Business Intelligence" },
  { name: "Sophia Brown", company: "Analytics Pro", department: "IT Security" },
  { name: "Scarlett Thomas", company: "Manufacturing Tech", department: "Property Management" },
  { name: "James Lopez", company: "Biotech Innovations", department: "Administration" },
  { name: "Emily Perez", company: "Healthcare IT", department: "Content" },
  { name: "Scarlett Hernandez", company: "Data Corp", department: "Sales" },
  { name: "David Harris", company: "Social Media Inc", department: "Strategy" },
  { name: "Ethan Garcia", company: "Spa & Wellness", department: "Business Intelligence" },
  { name: "Christopher Scott", company: "Retail Solutions", department: "Therapy" },
  { name: "Joseph Martinez", company: "Innovate Labs", department: "Operations" },
  { name: "William Smith", company: "Advertising Agency", department: "Innovation" },
  { name: "Emily Harris", company: "Biotech Innovations", department: "Sales" },
  { name: "Amelia Rivera", company: "Publishing House", department: "Renewable Energy" },
  { name: "Daniel Torres", company: "Manufacturing Tech", department: "Design Studio" },
  { name: "Andrew Hill", company: "Video Platform", department: "Therapy" },
  { name: "Isabella Hill", company: "Fitness Tech", department: "Innovation" },
  { name: "Zoey Campbell", company: "AI Solutions", department: "Design" },
  { name: "Benjamin Scott", company: "Spa & Wellness", department: "Operations" },
  { name: "Emma Hernandez", company: "Mobile First", department: "Research & Development" },
  { name: "James Allen", company: "Travel Tech", department: "Merchandising" },
  { name: "Emma Martinez", company: "BlockChain Ventures", department: "Production" },
  { name: "Christian Baker", company: "Cyber Security Plus", department: "Strategy" },
  { name: "Alexander Walker", company: "Platform Services", department: "Genetics" },
  { name: "Elizabeth Lewis", company: "Resort Management", department: "Data Science" },
  { name: "Ava Perez", company: "Global Enterprises", department: "Human Resources" },
  { name: "Joseph Young", company: "Spa & Wellness", department: "Athlete Relations" },
  { name: "David Lewis", company: "Hotel Chain", department: "Supply Chain" },
  { name: "Ethan Harris", company: "Web Innovations", department: "Consulting" },
  { name: "Isabella Rodriguez", company: "Hotel Chain", department: "IT Security" },
  { name: "Lily Campbell", company: "BlockChain Ventures", department: "Customer Support" },
  { name: "Ella Ramirez", company: "Event Management", department: "Planning" },
  { name: "Sophia Flores", company: "Fashion Tech", department: "Content" },
  { name: "Isabella Robinson", company: "Sports Management", department: "Consulting" },
  { name: "Matthew Nguyen", company: "Manufacturing Tech", department: "Logistics" },
  { name: "Daniel Martinez", company: "Social Media Inc", department: "Property Management" },
  { name: "Liam Martinez", company: "Music Streaming", department: "Design Studio" },
  { name: "Liam Rivera", company: "Music Streaming", department: "Athlete Relations" },
  { name: "Christian Ramirez", company: "Manufacturing Tech", department: "Training" },
  { name: "Lily Thomas", company: "Publishing House", department: "Sales" },
  { name: "Michael Carter", company: "Digital Marketing Co", department: "Medical Technology" },
  { name: "Sebastian Thomas", company: "Resort Management", department: "Human Resources" },
  { name: "Isabella Brown", company: "Music Streaming", department: "Health Science" },
  { name: "Avery Hall", company: "Catering Services", department: "Research & Development" },
  { name: "Zoey Taylor", company: "Web Innovations", department: "Clinical Trials" },
  { name: "Olivia Thompson", company: "BlockChain Ventures", department: "Research & Development" },
  { name: "Abigail Brown", company: "PR Solutions", department: "Consulting" },
  { name: "Emily Robinson", company: "Future Systems", department: "Training" },
  { name: "Nora Thomas", company: "Future Systems", department: "Consulting" },
  { name: "Emma Allen", company: "Entertainment Group", department: "Logistics" },
  { name: "Ryan Davis", company: "Cyber Security Plus", department: "Clinical Trials" },
  { name: "Chloe Mitchell", company: "Fashion Tech", department: "Accounting" },
  { name: "William Scott", company: "Analytics Pro", department: "Training" },
  { name: "Owen Miller", company: "BlockChain Ventures", department: "Genetics" },
  { name: "Lily Rodriguez", company: "Event Management", department: "Production" },
  { name: "Hannah Anderson", company: "Cyber Security Plus", department: "Strategy" },
  { name: "David Roberts", company: "Social Media Inc", department: "Training" },
  { name: "Evelyn Jackson", company: "Entertainment Group", department: "Marketing" },
  { name: "Sofia Jackson", company: "Fitness Tech", department: "Supply Chain" },
  { name: "Sebastian Robinson", company: "Software House", department: "Operations" },
  { name: "Emma Garcia", company: "PR Solutions", department: "Product Management" },
  { name: "Mia King", company: "Platform Services", department: "Operations" },
  { name: "Henry Roberts", company: "Healthcare IT", department: "Training" },
  { name: "Alexander Harris", company: "Fitness Tech", department: "Renewable Energy" },
  { name: "Lily Nguyen", company: "Mobile First", department: "Machine Learning" },
  { name: "Christopher Baker", company: "Hotel Chain", department: "Genetics" },
  { name: "Charlotte Taylor", company: "Retail Solutions", department: "Logistics" },
  { name: "Nora Thompson", company: "Pharmaceutical Co", department: "Property Management" },
  { name: "Emma Moore", company: "Catering Services", department: "Therapy" },
  { name: "Avery Nelson", company: "Publishing House", department: "Learning Solutions" },
  { name: "Nora Lopez", company: "Tech Solutions Inc", department: "Athlete Relations" },
  { name: "Evelyn Wright", company: "Real Estate Tech", department: "Planning" },
  { name: "Mia Walker", company: "Mobile First", department: "Sales" },
  { name: "Noah Lewis", company: "Hotel Chain", department: "IT Security" },
  { name: "Scarlett Torres", company: "Finance Tech", department: "Innovation" },
  { name: "Lily King", company: "Video Platform", department: "Clinical Trials" },
  { name: "Avery Campbell", company: "Video Platform", department: "Research & Development" },
  { name: "Olivia Clark", company: "Platform Services", department: "Content Acquisition" },
  { name: "Henry Brown", company: "Cloud Networks", department: "Business Intelligence" },
  { name: "Ella Sanchez", company: "Media Group", department: "DevOps" },
  { name: "Chloe Lewis", company: "Tech Solutions Inc", department: "Public Relations" },
  { name: "Owen Robinson", company: "Real Estate Tech", department: "Creative" },
  { name: "Avery Jones", company: "Manufacturing Tech", department: "Community Management" },
  { name: "James Lewis", company: "Publishing House", department: "Content Acquisition" },
  { name: "Lucas Rodriguez", company: "AI Solutions", department: "Broadcasting" },
  { name: "Ella Jones", company: "Pharmaceutical Co", department: "Health Science" },
  { name: "Sofia Adams", company: "Education Tech", department: "Quality Assurance" },
  { name: "Ella Harris", company: "Fitness Tech", department: "Strategy" },
  { name: "Ryan White", company: "Spa & Wellness", department: "Supply Chain" },
  { name: "Mia Smith", company: "Platform Services", department: "Content" },
  { name: "Michael Brown", company: "Smart Technologies", department: "Product Management" },
  { name: "Emma Lopez", company: "Energy Systems", department: "Design" },
  { name: "Elizabeth Carter", company: "Food Delivery Co", department: "Therapy" },
  { name: "Owen Jones", company: "Entertainment Group", department: "Business Intelligence" },
  { name: "Ava Hall", company: "Tech Solutions Inc", department: "Consulting" },
  { name: "Emma Garcia", company: "Travel Tech", department: "Research & Development" },
  { name: "Mia Anderson", company: "Hotel Chain", department: "Learning Solutions" },
  { name: "Jack Nguyen", company: "Catering Services", department: "Product Management" },
  { name: "Michael Wright", company: "Food Delivery Co", department: "Operations" },
  { name: "Ella Campbell", company: "Media Group", department: "Finance" },
  { name: "Elizabeth Carter", company: "Travel Tech", department: "Data Science" },
  { name: "Grace Anderson", company: "Transport Solutions", department: "Marketing" },
  { name: "David Walker", company: "Cloud Networks", department: "Genetics" },
  { name: "Grace Moore", company: "Travel Tech", department: "IT Security" },
  { name: "Daniel Sanchez", company: "Hotel Chain", department: "Accounting" },
  { name: "Matthew Torres", company: "Video Platform", department: "Renewable Energy" },
  { name: "Hannah Taylor", company: "Fitness Tech", department: "DevOps" },
  { name: "Owen Taylor", company: "Music Streaming", department: "Therapy" },
  { name: "Sofia Baker", company: "Catering Services", department: "Design" },
  { name: "James Walker", company: "Smart Technologies", department: "Operations" },
  { name: "Harper Martin", company: "Retail Solutions", department: "Research" },
  { name: "Andrew Baker", company: "Smart Technologies", department: "Renewable Energy" },
  { name: "Sophia Walker", company: "Finance Tech", department: "Planning" },
  { name: "William Harris", company: "Energy Systems", department: "Product Management" },
  { name: "Sebastian Baker", company: "Social Media Inc", department: "Public Relations" },
  { name: "Samuel Garcia", company: "Cloud Networks", department: "Content" },
  { name: "Sebastian Lee", company: "Cloud Networks", department: "Community Management" },
  { name: "Noah Jones", company: "Publishing House", department: "Design Studio" },
  { name: "Nora Mitchell", company: "Education Tech", department: "Athlete Relations" },
  { name: "Elizabeth Flores", company: "Global Enterprises", department: "Genetics" },
  { name: "Benjamin Clark", company: "Spa & Wellness", department: "Customer Support" },
  { name: "Zoey Perez", company: "Analytics Pro", department: "Content Acquisition" },
  { name: "David Martinez", company: "Food Delivery Co", department: "Design" },
  { name: "Mason Miller", company: "Data Corp", department: "Research" },
  { name: "Ryan Sanchez", company: "Retail Solutions", department: "Medical Technology" },
  { name: "Grace Jackson", company: "Fashion Tech", department: "Design Studio" },
  { name: "Jack King", company: "Analytics Pro", department: "Consulting" },
  { name: "Andrew Hernandez", company: "Media Group", department: "Editorial" },
  { name: "Benjamin Miller", company: "E-Commerce Hub", department: "Medical Technology" },
  { name: "Michael Hill", company: "Media Group", department: "Editorial" },
  { name: "Addison Scott", company: "Social Media Inc", department: "Marketing" },
  { name: "Ethan Allen", company: "Beauty Products", department: "Accounting" },
  { name: "Jack Harris", company: "Digital Dynamics", department: "Consulting" },
  { name: "Hannah Wright", company: "AI Solutions", department: "Finance" },
  { name: "Grace Jackson", company: "Nutrition Apps", department: "Content Acquisition" },
  { name: "Scarlett Garcia", company: "Global Enterprises", department: "Broadcasting" },
  { name: "Nathan Roberts", company: "Spa & Wellness", department: "Editorial" },
  { name: "Sophia Clark", company: "Gaming Studios", department: "Athlete Relations" },
  { name: "Nora Brown", company: "Music Streaming", department: "Therapy" },
  { name: "Abigail Nguyen", company: "Resort Management", department: "Development" },
  { name: "Abigail Gonzalez", company: "Real Estate Tech", department: "Legal" },
  { name: "Ella Allen", company: "Innovate Labs", department: "Public Relations" },
  { name: "Amelia Robinson", company: "Beauty Products", department: "Human Resources" },
  { name: "Daniel Perez", company: "Video Platform", department: "Data Science" },
  { name: "Joseph Johnson", company: "Platform Services", department: "Compliance" },
  { name: "Noah Lopez", company: "Biotech Innovations", department: "Marketing" },
  { name: "Addison Roberts", company: "Medical Devices", department: "Machine Learning" },
  { name: "Sofia Thomas", company: "Nutrition Apps", department: "Planning" },
  { name: "James Campbell", company: "Food Delivery Co", department: "Customer Support" },
  { name: "Joseph Taylor", company: "Global Enterprises", department: "Supply Chain" },
  { name: "Jack Martin", company: "Social Media Inc", department: "Sales" },
  { name: "Ryan Moore", company: "Catering Services", department: "DevOps" },
  { name: "Michael Green", company: "Innovate Labs", department: "Human Resources" },
  { name: "Benjamin Perez", company: "Global Enterprises", department: "Engineering" },
  { name: "Scarlett Gonzalez", company: "Hotel Chain", department: "Marketing" },
  { name: "Zoey Lopez", company: "Catering Services", department: "Innovation" },
  { name: "Isabella Wright", company: "Cyber Security Plus", department: "Data Science" },
  { name: "Evelyn Hernandez", company: "Web Innovations", department: "Renewable Energy" },
  { name: "Benjamin Thomas", company: "Global Enterprises", department: "Therapy" },
  { name: "Scarlett Clark", company: "Food Delivery Co", department: "Innovation" },
  { name: "Jack Garcia", company: "Video Platform", department: "Training" },
  { name: "Mason Hill", company: "Web Innovations", department: "Engineering" },
  { name: "Avery Williams", company: "Cloud Networks", department: "Broadcasting" },
  { name: "Ava Martinez", company: "Real Estate Tech", department: "Product Management" },
  { name: "William Hill", company: "Sports Management", department: "Therapy" },
  { name: "Nathan Miller", company: "BlockChain Ventures", department: "Booking Systems" },
  { name: "Sophia Thomas", company: "PR Solutions", department: "Design" },
  { name: "Alexander Young", company: "Cyber Security Plus", department: "Logistics" },
  { name: "James Brown", company: "Data Corp", department: "Marketing" },
  { name: "Emma Martin", company: "Mobile First", department: "Engineering" },
  { name: "Samuel Lee", company: "Video Platform", department: "Learning Solutions" },
  { name: "Nathan Garcia", company: "Publishing House", department: "Health Science" },
  { name: "Amelia Anderson", company: "Manufacturing Tech", department: "Public Relations" },
  { name: "Emma Mitchell", company: "Publishing House", department: "Property Management" },
  { name: "Ava Gonzalez", company: "Food Delivery Co", department: "Medical Technology" },
  { name: "Mia Lewis", company: "Spa & Wellness", department: "Merchandising" },
  { name: "Lucas Roberts", company: "Analytics Pro", department: "Learning Solutions" },
  { name: "Hannah Jones", company: "Data Corp", department: "Development" },
  { name: "Ava Green", company: "Global Enterprises", department: "Broadcasting" },
  { name: "Chloe Green", company: "Digital Marketing Co", department: "Learning Solutions" },
  { name: "Lily Adams", company: "Music Streaming", department: "Innovation" },
  { name: "Evelyn Garcia", company: "Video Platform", department: "Development" },
  { name: "Emma Rodriguez", company: "Nutrition Apps", department: "Renewable Energy" },
  { name: "David Gonzalez", company: "Music Streaming", department: "Legal" },
  { name: "Addison Walker", company: "Software House", department: "Content Acquisition" },
  { name: "Olivia Moore", company: "Pharmaceutical Co", department: "Quality Assurance" },
  { name: "Emily Rodriguez", company: "E-Commerce Hub", department: "Genetics" },
  { name: "Isabella Martin", company: "E-Commerce Hub", department: "Sales" },
  { name: "Sofia Robinson", company: "Gaming Studios", department: "Broadcasting" },
  { name: "Zoey Mitchell", company: "PR Solutions", department: "Development" },
  { name: "James Scott", company: "Tech Solutions Inc", department: "Legal" },
  { name: "Ethan Jones", company: "Travel Tech", department: "Research" },
  { name: "Nora Rodriguez", company: "Real Estate Tech", department: "Creative" },
  { name: "Nora Green", company: "Beauty Products", department: "Editorial" },
  { name: "Victoria King", company: "Publishing House", department: "Administration" },
  { name: "Samuel Moore", company: "Innovate Labs", department: "Clinical Trials" },
  { name: "Charlotte Thomas", company: "Smart Technologies", department: "Design" },
  { name: "David Smith", company: "Software House", department: "DevOps" },
  { name: "Lily Ramirez", company: "Nutrition Apps", department: "Clinical Trials" },
  { name: "Michael Garcia", company: "Spa & Wellness", department: "Administration" },
  { name: "Ella Baker", company: "Digital Marketing Co", department: "Renewable Energy" },
  { name: "Matthew Roberts", company: "Platform Services", department: "Merchandising" },
  { name: "Elizabeth Carter", company: "Smart Technologies", department: "Research & Development" },
  { name: "Addison Lewis", company: "Digital Dynamics", department: "Design" },
  { name: "Sophia Nelson", company: "Gaming Studios", department: "Engineering" },
  { name: "Daniel Ramirez", company: "Mobile First", department: "Research & Development" },
  { name: "Joseph Hill", company: "Digital Dynamics", department: "Development" },
  { name: "Jack Hill", company: "Media Group", department: "Operations" },
  { name: "Victoria Robinson", company: "Spa & Wellness", department: "DevOps" },
  { name: "David Robinson", company: "Cyber Security Plus", department: "DevOps" },
  { name: "Emma Green", company: "Food Delivery Co", department: "Merchandising" },
  { name: "Nathan Mitchell", company: "Energy Systems", department: "Medical Technology" },
  { name: "Ella Flores", company: "Tech Solutions Inc", department: "Business Intelligence" },
  { name: "Emily Walker", company: "Entertainment Group", department: "Therapy" },
  { name: "Addison Thomas", company: "Pharmaceutical Co", department: "Broadcasting" },
  { name: "Isaac Wright", company: "Tech Solutions Inc", department: "Strategy" },
  { name: "Sophia Harris", company: "Fashion Tech", department: "Health Science" },
  { name: "Scarlett Lopez", company: "Pharmaceutical Co", department: "Customer Support" },
  { name: "Scarlett Martin", company: "Platform Services", department: "Human Resources" },
  { name: "Benjamin Roberts", company: "Music Streaming", department: "Customer Support" },
  { name: "Nora Hernandez", company: "Music Streaming", department: "Design Studio" },
  { name: "Olivia Harris", company: "Biotech Innovations", department: "Editorial" },
  { name: "Scarlett Martinez", company: "Food Delivery Co", department: "IT Security" },
  { name: "Joseph Williams", company: "Spa & Wellness", department: "Legal" },
  { name: "Lucas Clark", company: "Energy Systems", department: "Innovation" },
  { name: "Lily Thomas", company: "Gaming Studios", department: "Renewable Energy" },
  { name: "Ella Johnson", company: "Cloud Networks", department: "Content Acquisition" },
  { name: "Emily Thomas", company: "Publishing House", department: "IT Security" },
  { name: "Charlotte Moore", company: "Pharmaceutical Co", department: "IT Security" },
  { name: "Emma Sanchez", company: "Digital Marketing Co", department: "Editorial" },
  { name: "Benjamin Gonzalez", company: "Cloud Networks", department: "Clinical Trials" },
  { name: "Jack Davis", company: "Social Media Inc", department: "Legal" },
  { name: "Sofia Martinez", company: "Resort Management", department: "Accounting" },
  { name: "Chloe Lopez", company: "Retail Solutions", department: "Game Design" },
  { name: "Christopher Rodriguez", company: "Biotech Innovations", department: "Machine Learning" },
  { name: "Isaac Torres", company: "Nutrition Apps", department: "Merchandising" },
  { name: "Henry Lopez", company: "Music Streaming", department: "Creative" },
  { name: "Chloe Jones", company: "Digital Dynamics", department: "Machine Learning" },
  { name: "Lucas Sanchez", company: "E-Commerce Hub", department: "Finance" },
  { name: "Mia Taylor", company: "BlockChain Ventures", department: "Therapy" },
  { name: "Nathan Hall", company: "Retail Solutions", department: "Data Science" },
  { name: "Ava Baker", company: "Media Group", department: "Merchandising" },
  { name: "Jack Davis", company: "Catering Services", department: "Merchandising" },
  { name: "Michael Campbell", company: "Digital Dynamics", department: "Human Resources" },
  { name: "Olivia Taylor", company: "Retail Solutions", department: "Human Resources" },
  { name: "Alexander Adams", company: "AI Solutions", department: "Clinical Trials" },
  { name: "Noah Rodriguez", company: "Smart Technologies", department: "Data Science" },
  { name: "Noah Baker", company: "Fitness Tech", department: "Supply Chain" },
  { name: "Henry Martin", company: "Web Innovations", department: "Creative" },
  { name: "William Sanchez", company: "Fitness Tech", department: "Public Relations" },
  { name: "Michael Campbell", company: "Tech Solutions Inc", department: "Editorial" },
  { name: "Jack Robinson", company: "Healthcare IT", department: "Administration" },
  { name: "Benjamin Brown", company: "Event Management", department: "Development" },
  { name: "Christian Wright", company: "Finance Tech", department: "Data Science" },
  { name: "Mason Davis", company: "Fashion Tech", department: "Medical Technology" },
  { name: "Evelyn Hernandez", company: "Nutrition Apps", department: "Operations" },
  { name: "James Martinez", company: "Entertainment Group", department: "Athlete Relations" },
  { name: "Andrew Ramirez", company: "Music Streaming", department: "Research & Development" },
  { name: "Christopher Nelson", company: "Biotech Innovations", department: "Game Design" },
  { name: "Mason Carter", company: "Innovate Labs", department: "Game Design" },
  { name: "Elizabeth Thompson", company: "Future Systems", department: "Renewable Energy" },
  { name: "James Rodriguez", company: "Finance Tech", department: "Broadcasting" },
  { name: "Abigail Thomas", company: "Finance Tech", department: "Broadcasting" },
  { name: "Benjamin Rivera", company: "Pharmaceutical Co", department: "Renewable Energy" },
  { name: "Grace Green", company: "Tech Solutions Inc", department: "Human Resources" }
]
